name: "Lint Markdown"

on:
  push:
  pull_request:

jobs:
  lint-changelog:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Locate or create markdownlint config
      run: |
        ls -la $GITHUB_WORKSPACE
        if [ ! -f $GITHUB_WORKSPACE/.markdownlint.json ]; then
          echo "Using template markdownlint config"
          cat << EOF > $GITHUB_WORKSPACE/.markdownlint.json
            {
              "default": true,
              "MD029": {"style": "ordered" },
              "MD031": false,
              "MD033": false,
              "MD034": false,
              "MD040": false,
              "MD041": false
            }
        EOF
        fi
        ls -la $GITHUB_WORKSPACE

    - name: Run markdownlint
      uses: docker://avtodev/markdown-lint:master
      with:
        config: '$GITHUB_WORKSPACE/.markdownlint.json'
        args: '**.md'
